### PR TITLE
Fix TracerV Trigger Generation When Tracing Is Disabled

### LINKED ISSUE #600: Decouple TracerV-enable and Trigger-enable
In the current FireSim version, in order to use any bridge that may depend on a trigger, the TracerV bridge driver needs to be enabled.
I previous versions of FireSim, the trigger could be used in any AGFI that had the TracerV widget synthesized (all of them, by default), without having the trace written out to disk.

As a result, in order to use Autocounter in the current version of FireSim, the user must also output a tracefile (which really slows down simulation, because of writing the file to disk).

The rational behind the change was that TracerV was hurting FMR when it was not being used, since it was still offloading token to the host despite them not being written to disk.
The potential solution is to separate trigger-enable and tracer-enable

### PR DESCRIPTION
**Pull request by davidbiancolin**
In a regression introduced by multiclock support, if you weren't collecting an instruction trace with TracerV it's trigger sources would be disabled, which would effectively disable AutoCounter. This PR fixes that by separating trace disable from the trigger specification. 

Resolves #600. Perhaps a better longer term solution might be to pull the trigger source handling out of tracerV entirely.

### CODE REVIEW

File: sim/firesim-lib/src/main/cc/bridges/tracerv.cc [hunk 1]
```diff
@@ -188,15 +186,15 @@ void tracerv_t::init() {
...
               this->trigger_start_insn, this->trigger_start_insn_mask,
               this->trigger_stop_insn, this->trigger_stop_insn_mask);
     }
     else
     {
-      // Biancolin: should we not error here?
+      // Writing 0 to triggerSelector permanently enables the trigger
       write(this->mmio_addrs->triggerSelector, this->trigger_selector);
-      printf("TracerV: No trigger selected. Collecting trace from %lu to %lu cycles\n", 0, ULONG_MAX);
+      printf("TracerV: No trigger selected. Enable trigger enabled from %lu to %lu cycles\n", 0, ULONG_MAX);
```
Comment (alonamid) [inline sim/firesim-lib/src/main/cc/bridges/tracerv.cc:197]: "Enable trigger enabled"?
